apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: deploy-nginx 
spec: 
  replicas: 3 
  selector: 
    matchLabels: 
    app: my-nginx 
  template: 
    metadata: 
      name: my-nginx-pod 
      labels: 
        app: my-nginx 
    spec:
      containers:
      - name: ngingx-ctn
        image: nginx
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ngninx-lb
spec:
  ports:
  - name: nginx-port
    targetPort: 80
    port: 80
  selector:
    app: my-nginx
  type: LoadBalancer
